### ISSUE TITLE
Print # on Windows creates file with only Unix LF

### ISSUE THREAD

**Issue by barryple** [smallbasic/SmallBASIC#100]
Using Windows 10 and SmallBasic 0.12.18 

open "junk.txt" for output as #1
print #1, "test"
close #1

creates txt file that when opened with Notepad++ shows file as Unix (LF) instead of Windows (CR/LF) and doesn't open with other legacy basics.  Tested sbasic.exe, sbasicg.exe, and sbasicg64.exe

thanks

**Comment by chrisws** [comment]
Fixed in release 12.19
