### ISSUE TITLE
Socket: Client doesn't receive byte with value 13

### ISSUE THREAD

**Issue by Joe7M** [smallbasic/SmallBASIC#112]
open "SOCL:127.0.0.1:10000" as #1
for ii = 0 to n
   data[ii] = bgetc(1)
next ii

Every time the server sends a byte with the decimal value of 13 bgetc(1) does not receive the byte. Otherwise data transfer is fine.

In file src/common/inet2.c line 172 is written:

if (ch != '\015') {       // ignore it
        buf[count] = ch;
        count += bytes;         // actually ++
      }

I think this might be the reason why byte with value 13 is not received, because decimal 13 is octal 15.

**Comment by chrisws** [comment]
Test programs, 

server.bas
```
while 1
  open "SOCL:10000" as #1
  print "ready"
  i=13
  bputc #1, i
  delay 1000
  close #1
wend
```
client.bas
```
repeat
  delay 100
  open "SOCL:127.0.0.1:10000" as #1
until not eof(1)
print bgetc(1)
close #1
```

**Comment by chrisws** [comment]
Fixed, thanks for reporting the issue !
