### ISSUE TITLE
bug or feature????

### ISSUE THREAD

**Issue by jsalai49** [smallbasic/SmallBASIC#114]
Windows, smallbasic_12_20 but earlier too!!!!

```
a=77.603
?a
?round(a,3)
?"now why not: 77.603 ????"
pause
end
```

gives always 77.60299999999999

Cheers!

Oooouuuups - on Android too!!!!!!

and sometimes gives xxx.yyy00000000001 as result!
e.g. 172.121

**Comment by H1N1-dev** [comment]
Floating point in programming has many bugs. And, in SmallBasic too. I recommend read this site - https://0.30000000000000004.com/ for understand the bug.

**Comment by jsalai49** [comment]
Thanks for your kind answer,
of course, I know the quirks about floats. and I know that this is a "feature", bcs the designers of modern processors and their software followers striped out all parts and traces of BCD arithmetics, not to speak of even slower string calculations, of course to get more and more speed.
Not to speak of dinosaur era with CIP and SIP processor, where Commercial Instruction Processors work slow, but accurately.

Now, back to the "bug". Not meant to be criticism, but I'd like if there would be some simple solution. The fact is that this happens not very often, and I know how to handle the problem.
Anyway, thanks for your answer!
Wish you all the best, and good health!
Cheers!
Josip

**Comment by H1N1-dev** [comment]
I am dont know, what this.
I tried convert number to string and cut it, but after converting string again to number, then i see this bug.
I have idea how fix this, but is a little hard, i can't understand source code :(

**Comment by jsalai49** [comment]
As this is an issue concerning only an output, this remedy may help. In the code, I leave the orig value.

def rd(x)=iff(frac(x)=0,x,trim(format("###########.###",x)))
?rd(77.603), rd(172.121)
pause
end

giving 77.602 (stripping the 9's)!!!
with 172.121 it does it fine

But unfortunately, this opens an other **bug** (!?!?!) concerning the **format** function. Unlike the **round** or **using** this only strips the remaining... In concrete situation it is not a problem and I could do a bit string juggling, but there is not important.
But converting the corrected string to number will be a problem.

Thanks, anyway for your efforts
