### ISSUE TITLE
Wrong angles.

### ISSUE THREAD

**Issue by H1N1-dev** [smallbasic/SmallBASIC#117]
Angles wrong there.
ATAN2() thinks that 0 degrees in down side of screen.
But, ARC function thinks that 0 degrees is right side.

`'Bug?`
`color rgbf(0.3, 0.3, 0.3) ' Color the axes`

`line xmax/2, 0, xmax/2, ymax`
`line 0, ymax/2, xmax, ymax/2`

`color rgbf(1, 0, 0)`
`arc xmax/2, ymax/2, 200, 0, 0.1 ' 0 degrees.`

`' Zero angle its right side, yes?`
`ang = atan2(10, 0) ' X=10, Y=0. Right side?`

`print deg(ang) 'No! Right is 90 degrees?`
...
Also, atan2() range of output is `-180 ~ 180`, and ARC range of angle is `0 ~ 360`.
But why?

**Comment by jsalai49** [comment]
https://smallbasic.github.io/reference/718.html

**Comment by H1N1-dev** [comment]
@jsalai49 thanks for help :)

**Comment by H1N1-dev** [comment]
Now i am learned, atan2() arguments is (y, x), NOT (x, y)
And, `atan2(5, 0)` means Y=5 and X=0.
This is standard function implementation.
