### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by ptravnik** [smallbasic/SmallBASIC#120]
Make fails with an error:

var_map.c:21:10: fatal error: lib/jsmn/jsmn.h: No such file or directory
   21 | #include "lib/jsmn/jsmn.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by ptravnik** [comment]
After forced jsmn install, further fails with:

make[2]: *** No rule to make target '../../lib/lodepng/lodepng.cpp', needed by '../../lib/lodepng/lodepng.o'.  Stop.

**Comment by chrisws** [comment]
The dependencies jsmn, lodepng, miniaudio and stb are handled as git sub-modules. 

This makes it easier to keep up with changes to these libraries.

You should try running the autogen shell script, this handles pulling in the library code

$ sh autogen.sh

This assume you have installed git.
