### ISSUE TITLE
win sbasicg 12.20

### ISSUE THREAD

**Issue by jsalai49** [smallbasic/SmallBASIC#122]
Win, sbasicg, 12.20
an interesting observation, probably already fixed

<code>
dim z(),y()
u=35
v=50
y << u+0,v+0
?y:pause ' interestingly this works
z << u,v
'returns an error "COMMAND SEPARATOR FOUND ','" 
</code>

**Comment by jsalai49** [comment]
I messed something up in the message
an interesting observation, probably already fixed

dim z(),y()
u=35
v=50
y << u+0,v+0
?y:pause ' interestingly this works
z << u,v
'returns an error "COMMAND SEPARATOR FOUND ','"

**Comment by chrisws** [comment]
Fixed - thanks for reporting the issue !
