### ISSUE TITLE
AppImage cannot run on Ubuntu bionic

### ISSUE THREAD

**Issue by probonopd** [smallbasic/SmallBASIC#128]
Hi, thanks for making an AppImage. However, it looks like it was built on too new a system and hence cannot run on Ubuntu bionic:

```
AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
```

Could you please produce the AppImage on an older build system, such as the oldest still-supported Ubuntu release, which currently is bionic?

Then we could add SmallBASIC to https://appimage.github.io/.
Thanks!

Reference:
https://github.com/AppImage/appimage.github.io/pull/2636

**Comment by chrisws** [comment]
Thanks for your report. I'll try building it under the older Ubuntu version and see how it goes.

**Comment by chrisws** [comment]
I've rebuilt the packages under bionic and have attached them to the release. 

The files are:
SmallBASIC-FLTK_12.23-2-x86_64.AppImage
SmallBASIC-SDL_12.23-2-x86_64.AppImage

Please let me know if this works for you.

Cheers
Chris

**Comment by probonopd** [comment]
Hello Chris, thank you very much - I confirm that it is working now :+1:
