### ISSUE TITLE
How to run examples code?

### ISSUE THREAD

**Issue by 3oheicrw** [smallbasic/SmallBASIC#138]
Well, I use sbasic examples\3dtorus.bas, it keeps running but showed nothing. If I pass -v to sbasic I could see clearly it stuck at Initializing something. Meanwhile sbasic -m . examples\modules\gui.bas works. I have no idea why. The document about how to actual use sbasic.exe is lacking. sbasic -h gives only a handful of not easy to understand descriptions.

**Comment by Joe7M** [comment]
sbasic is a console version without any graphic output. You can use sbasic for text-only output directly to the command-line.  Additionally you can use sbasic in combination with a module which creates his own graphics output like raylib or nuklear.

If you want to run 3dtorus.bas,  please use sbasicg which uses SDL2 as graphics output. You can start sbasicg without any parameters. It will then run the build-in editor.

**Comment by 3oheicrw** [comment]
It's better to use sbasicg -r to run it directly. The IDE is too ugly and difficult to use. Not everyone is Emacs users or familiar with keyboard driven editors.
