### ISSUE TITLE
JSON support?

### ISSUE THREAD

**Issue by shlwapi** [smallbasic/SmallBASIC#155]
Something like the Python API?

https://www.w3schools.com/python/python_json.asp

**Comment by chrisws** [comment]
Yes JSON is supported.

Here's an example: https://github.com/smallbasic/smallbasic.github.io/blob/58e9d03ec5260ff9c29a6067f50988e72c3cabb1/samples/node/1266.bas

**Comment by shlwapi** [comment]
> Yes JSON is supported.
> 
> Here's an example: https://github.com/smallbasic/smallbasic.github.io/blob/58e9d03ec5260ff9c29a6067f50988e72c3cabb1/samples/node/1266.bas

This is about reading JSON. What about writting JSON? Something like the Python API I mentioned above.

**Comment by chrisws** [comment]
Sorry for the late reply. Actually you can write JSON by passing a map variable to `STR()`, like this:

```
foo={}
foo.dog = "jessie"
foo.hello = "you"
print str(foo)
```
prints:
`{"dog":"jessie","hello":"you"}`

**Comment by chrisws** [comment]
Also: another example worth examining:

https://github.com/smallbasic/SmallBASIC/blob/master/samples/distro-examples/games/2048.bas

It would be possible to write an extension module with more extensive JSON support.
