### ISSUE TITLE
Run with shebang on Linux?

### ISSUE THREAD

**Issue by shlwapi** [smallbasic/SmallBASIC#156]
It's very useful to have scripts able to run by themselves like ./foo.bas by having something like `#!/usr/bin/sbasic` or `#!/usr/bin/env sbasic` at the beginning of the scripts. Does this already supported or not? It's not as simple as you put this line at the beginning of code and it suddenly able to run like that. It needs support from the interpreter too.

**Comment by chrisws** [comment]
Yes that should be supported. Please let me know if this isn't working for you.

**Comment by va0dl914** [comment]
> Yes that should be supported. Please let me know if this isn't working for you.

So does it work on Cygwin or MSYS2 too?
