### ISSUE TITLE
Smallbasic crashes on android

### ISSUE THREAD

**Issue by grassmik** [smallbasic/SmallBASIC#160]
This code snippet causes smallbasic 12.23  crashes on android:

for i=0 to 100
 print i
next i
input "test", t

**Comment by Joe7M** [comment]
a workaround until the bug is fixed seems to be:

```
for i=0 to 100
print i
next i
showpage
input "test", t
```

**Comment by chrisws** [comment]
Thanks so much for reporting this!

I've seen the corresponding stack trace in the android studio reports, but never found out how to replicate it until now

**Comment by chrisws** [comment]
The has been now been released so closing the issue as resolved.
