### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by jsalai49** [smallbasic/SmallBASIC#162]
There is probably an ongoing version - 25...
Unfortunately, at Google play there is is still version 23...
As in v24 there were many improvements these are not applicable on Android.
I understand that there may be issues to compile Android v24, so I just like to know when could we expect a synchronized version - win - lin - and.

Thanks for your efforts and attention, and take care!

**Comment by chrisws** [comment]
v25 is available on the play store if you sign up as a beta tester.
I will to make another beta update sonn then potentially push this as a release before the end of the year.
