### ISSUE TITLE
Build both `sbasic`, `sbasicg` and `sbasicw` in the same build?

### ISSUE THREAD

**Issue by iahung2** [smallbasic/SmallBASIC#199]
I found it will only build one of them each build. For example, I passed `--enable-sdl --enable-web` (`./configure --help` doesn't list `--enable-console` so I think the console version will always be built), I found only the SDL version is built.

p/s: I'm using MSYS2.

**Comment by iahung2** [comment]
@chrisws

**Comment by chrisws** [comment]
Sorry it's not possible to build everything all at once.  You could work around this with a script.

Yes console build is the default build target.
