### ISSUE TITLE
Forum problem and 2 questions-requests.

### ISSUE THREAD

**Issue by Achaean** [smallbasic/SmallBASIC#56]
**Hi!** :-)

1) Does the SDL version have (or will have) an IDE as the old one?

2) Have (or will have) Unicode support (for non-Latin charsets)?

3) Forum registration seems to be closed and password recovery don't works.

All the best!
A.

**Comment by chrisws** [comment]
1. Yes! Use the right mouse button to toggle on the editor, then click on a .bas file to start editing. You can also use the -e command line option to load the editor at startup. The editor has a more sparse appearance but actually has more features than the old one, for example step-thru debugging. 
2. Unicode is not yet supported, sorry.
3. Sourceforge ended email support for hosted web applications. There's a couple of alternative forums listed under the "links" page.
