### ISSUE TITLE
IMAGE problems copying screen pixels

### ISSUE THREAD

**Issue by MrZoolook** [smallbasic/SmallBASIC#66]
In the Android version, I am trying to use a piece of code to scroll the entire screen up some number of pixels. I figured using the **image** commands would be easiest and faster. However, I can't seem to copy the area (or reprint it) exactly. It looks as if somehow, the value of each pixels red and blue componant is swapped. (screenshot included for posterity)
![screenshot_2018-04-24-00-05-53 01](https://user-images.githubusercontent.com/22412099/39157658-c09d1c42-4753-11e8-9b62-142fe8e45662.png)

The code listed here should copy the 6 boxes exactly, but doesn't on all 3 Android devices I tried it on. I don't have a PC/iOS/other device to try it on. Version used is Android 0.12.11, but I've tried earlier versions to no avail.
```
cls
for z=0 to 255
  for t=0 to 255
    pset t+000,z,rgb(255-z,255-t,255-t)
    pset t+257,z,rgb(255-t,255-z,255-t)
    pset t+514,z,rgb(255-t,255-t,255-z)
    pset z+000,(t/4)+260,rgb(255-t,0,0)
    pset z+257,(t/4)+260,rgb(0,255-t,0)
    pset z+514,(t/4)+260,rgb(0,0,255-t)
  next
next
z=image(0,0,xmax,325)
z.show(0,350)
```
There is also some odd behavior when redrawing an image captured this way, if you try redisplaying it outside the screen, but apparently only in the vertical directions. My non-exhastive tests seem to indicate the horizontal placement of an image works fine.

Is this expected, or a bug?

**Comment by chrisws** [comment]
I tried your code on the desktop version (linux) and it displays correctly so it must be an issue with android specific code. It's not expected - thanks for reporting the bug!

I'll try and include a fix in the next update.

**Comment by MrZoolook** [comment]
Thank you for the update, Chris.

**Comment by chrisws** [comment]
This issue should be resolved now, so closing it.
