### ISSUE TITLE
How to compile SmallBASIC for VTech Helio PDAs?

### ISSUE THREAD

**Issue by tomrow** [smallbasic/SmallBASIC#67]
I have a VTech Helio PDA with an old version of SmallBASIC on it, I was wondering if it is possible to compile this new version for it and how I might go about doing that

**Comment by chrisws** [comment]
This is more or less not going to be possible. There doesn't seem to be any available development tools for this obsolete device. If they could be obtained from somewhere, it would still be a lot of work but there wouldn't be too many people who would benefit from the effort.

**Comment by tomrow** [comment]
@chrisws That's too bad. I think I may have found some sort of SDK for the device but I haven't tried it. Might be a good thing to look in to.
