### ISSUE TITLE
Windows version using numeric keypad with NumLock

### ISSUE THREAD

**Issue by MrZoolook** [smallbasic/SmallBASIC#81]
Using the latest Windows version, if I start the program with NumLock turned on, they keypad buttons produce BOTH the number and it's (un-numlocked) action. As in, pressing the '4' button types '4' in the program, but also moves the cursor left, pressing '9' moves the cursor up a page as the 9 is also the PageUp key... etc.

At this point, toggling off NumLock turns the keys into the number only, as if the program is reversing the state of the NumLock function.

HOWEVER, if I start the program with NumLock turned off, the program recognises the state of NumLock, and the keypad behaves as expected, with the NumLock state being recognised properly, and the keys working as expected with or without Numlock.

**Comment by chrisws** [comment]
I've looked at this previously but didn't get anywhere. I think your investigation notes might be useful so I'll take another look soon.

**Comment by chrisws** [comment]
This should now be fixed, let me know if you have any further issues.

**Comment by MrZoolook** [comment]
OK, well not sure whether I should open a new bug or not regarding this fix.

Numlock handling is fixed in the update, but with Numlock turned on, the rest of the keyboard isn't responding. To actually type code, I need to turn Numlock off.

**Comment by chrisws** [comment]
Someone mentioned this on the syntaxbomb forum. I will make a fix and
upload new .exe's soon

Cheers,
Chris
