### ISSUE TITLE
Number of columns and rows

### ISSUE THREAD

**Issue by programandala-net** [smallbasic/SmallBASIC#85]
I've searched the docs but it seems there's no way for a SmallBASIC program to know the current size of the terminal, right? For example, functions like `cols()` and `rows()`.

**Comment by chrisws** [comment]
You can use the `XMAX` and `YMAX` constants to get the dimensions of the screen in pixels. Then you can use the `TXTH` and `TXTW` functions to divide this by the width and height of a single character (in pixels). This will give the character rows and columns of the screen.

```
print int(xmax/txtw("W"))
print int(ymax/txth("W"))

```
